### ISSUE TITLE
Throws error when consecutive values are the same

### ISSUE THREAD

**Issue by jyjblrd** [Bersaelor/SwiftSplines#1]
If two consecutive values are the same, `Exceeded maximum iteration limit.` error is thrown.

For example, this will not work:
```
functionVariable = Spline(
    arguments: [0.0, 2],
    values:    [0.1, 0.1]
).f
```

I'm not sure if this is an intended result, but perhaps an error like `consecutive values cannot be the same` should be thrown to avoid confusion. Its not a huge bug. Thanks for making this libary.

**Comment by Bersaelor** [comment]
Thank you for the find, that is indeed a bug, consecutive values being the same should be no problem, as that should lead to a constant function.

I assume the matrix will just be degenerate, as the coefficients should all be zero, that should be the most common edge case. Good QA work @jyjblrd !

**Comment by Bersaelor** [comment]
Basically, the linear algebra systems will look like this:

```
 2 1   d1   0
 1 2   d2 = 0 
```
or

```
2 1 0    d1     0
1 4 1  * d2  =  0
0 1 2    d3     0
```

for which the solution is trivial, just that the sparse matrix solver goes haywire. Seems like we need to put an `if x_vec === 0` and treat that case separately.

**Comment by Bersaelor** [comment]
Please try again with the version 0.3.0  @jyjblrd

**Comment by jyjblrd** [comment]
Thanks for the incredibly fast fix! 

There is no way I could understand the linear algebra behind splines myself, so your library has been extremely useful.
